* Added the status_all command   * Better handling of determining which processes are running   * Properly returning status codes   * Added the DIETIME variable for restarting

diff --git a/flint b/flint
--- a/flint
+++ b/flint
@@ -6,13 +6,14 @@ MINSPARE=4
 MAXSPARE=32
 MAXCHILDREN=32
 MAXREQUESTS=100
+DIETIME=3
 METHOD=prefork
 RUN_DIR="/var/run/django"
 FASTCGI_USER="www-data"
 
 [ -e /etc/flint.conf ] && . /etc/flint.conf;
 
-VERSION_STR="flint 1.1.2"
+VERSION_STR="flint 1.1.3"
 
 is_root_or_die() {
 	if [ $(id -u) != "0" ]; then
@@ -34,6 +35,40 @@ is_project_or_die() {
 	fi
 }
 
+is_running() {
+	pidfile=$1
+	project=$2
+	virtualenv=$3
+	[ ! -f "$pidfile" ] && return 1
+
+	pid=`cat $pidfile`
+
+	[ ! -d "/proc/$pid" ] && return 1
+
+    cmd=`cat /proc/$pid/cmdline | tr '\0' ' ' | grep -c "$virtualenv/bin/python $project/manage.py"`;
+	[ $cmd -eq 1 ] && return 0 || return 1
+}
+
+status() {
+	project_name=$1
+	is_project_or_die $project_name
+
+	virtualenv="$VIRTUALENV_ROOT/$project_name"
+	project="$DJANGO_ROOT/$project_name"
+	socket="$RUN_DIR/$project_name-fastcgi.sock"
+	pidfile="$RUN_DIR/$project_name.pid"
+
+	echo -n " * Checking status of FastCGI for $project_name... "
+
+	if is_running "$pidfile" "$project" "$virtualenv"; then
+		echo "running."
+		return 0
+	else
+		echo "not running"
+		return 1
+	fi
+}
+
 start() {
 	is_root_or_die
 	project_name=$1
@@ -42,7 +77,7 @@ start() {
 	virtualenv="$VIRTUALENV_ROOT/$project_name"
 	project="$DJANGO_ROOT/$project_name"
 	socket="$RUN_DIR/$project_name-fastcgi.sock"
-	pid="$RUN_DIR/$project_name.pid"
+	pidfile="$RUN_DIR/$project_name.pid"
 
 	if [ ! -d $RUN_DIR ]; then
 		mkdir $RUN_DIR
@@ -51,12 +86,13 @@ start() {
 	chown $FASTCGI_USER $RUN_DIR
 
 	echo -n " * Starting FastCGI for $project_name... "
-	if [ -f $pid ]; then
+	if is_running "$pidfile" "$project" "$virtualenv"; then
 		echo "Already running. Not doing anything."
-		return
+		return 0
 	fi
 
-	su $FASTCGI_USER -c "$virtualenv/bin/python $project/manage.py runfcgi socket=$socket pidfile=$pid minspare=$MINSPARE maxspare=$MAXSPARE maxchildren=$MAXCHILDREN maxrequests=$MAXREQUESTS method=$METHOD daemonize=true" && echo OK || echo Failed
+	su $FASTCGI_USER -c "$virtualenv/bin/python $project/manage.py runfcgi socket=$socket pidfile=$pidfile minspare=$MINSPARE maxspare=$MAXSPARE maxchildren=$MAXCHILDREN maxrequests=$MAXREQUESTS method=$METHOD daemonize=true" && echo OK || echo Failed
+	return $?
 }
 
 stop() {
@@ -65,20 +101,24 @@ stop() {
 	is_project_or_die $project_name
 
 	socket="$RUN_DIR/$project_name-fastcgi.sock"
-	pid="$RUN_DIR/$project_name.pid"
+	pidfile="$RUN_DIR/$project_name.pid"
+	virtualenv="$VIRTUALENV_ROOT/$project_name"
+	project="$DJANGO_ROOT/$project_name"
 
 	echo -n " * Stopping FastCGI for $project_name... "
 
-	if [ ! -f $pid ]; then
+	if is_running "$pidfile" "$project" "$virtualenv"; then
+		kill `cat $pidfile`
+		status=$?
+		rm $pidfile
+		rm $socket
+
+		[ $status -eq 0 ] && echo "OK" || echo "Failed"
+		return $status
+	else
 		echo "Already stopped"
-		return
+		return 0
 	fi
-
-	kill `cat $pid`		
-	rm $pid
-	rm $socket
-
-	echo "OK"
 }
 
 restart_dead_project() {
@@ -86,67 +126,104 @@ restart_dead_project() {
 	project_name=$1
 	is_project_or_die $project_name
 
-	pid_file="$RUN_DIR/$project_name.pid"
-	if [ ! -f $pid_file ]; then
+	pidfile="$RUN_DIR/$project_name.pid"
+	virtualenv="$VIRTUALENV_ROOT/$project_name"
+	project="$DJANGO_ROOT/$project_name"
+
+	echo -n " * Starting FastCGI for $project_name... "
+	if is_running "$pidfile" "$project" "$virtualenv"; then
+		echo "Already running. Doing nothing."
+		return 0
+	else
 		echo "No PID file for $project_name. Restarting."
 		start $project_name
-		return
-	fi
-
-	pid=`cat $pid_file`
-	is_running=`ps -p $pid | grep -c $pid`
-	if [ $is_running -eq 0 ]; then
-		echo "PID file present but no matching process for $project_name. Restarting."
-		rm $pid_file
-		start $project_name
+		return $?
 	fi
 }
 
 restart_dead() {
 	is_root_or_die
+	errors=0
 	for project in `ls $DJANGO_ROOT`; do
 		restart_dead_project $project
+		[ ! $? -eq 0 ] && errors=$((errors+1))
 	done
+	
+	return $errors
 }
 
 start_all() {
 	is_root_or_die
+	errors=0
 	for project in `ls $DJANGO_ROOT`; do
 		start $project
+		[ ! $? -eq 0 ] && errors=$((errors+1))
 	done
+	
+	return $errors
 }
 
 stop_all() {
 	is_root_or_die
+	errors=0
 	for project in `ls $DJANGO_ROOT`; do
 		stop $project
+		[ ! $? -eq 0 ] && errors=$((errors+1))
 	done
+	
+	return $errors
 }
 
+status_all() {
+	errors=0
+	for project in `ls $DJANGO_ROOT`; do
+		status $project
+		[ ! $? -eq 0 ] && errors=$((errors+1))
+	done
+
+	return $errors
+}
+
+errcode=0
 case "$1" in
 	start_all)
 		start_all
+		errcode=$?
 	;;
 	stop_all)
 		stop_all
+		errcode=$?
 	;;
 	restart_all)
 		stop_all
+		errcode=$?
+		[ ! -z "$DIETIME" ] && sleep $DIETIME
 		start_all
+		[ $errcode -eq 0 ] && errcode=$?
 	;;
 
 	start)
 		start $2
+		errcode=$?
 	;;
 	stop)
 		stop $2
+		errcode=$?
 	;;
 	restart)
 		stop $2
+		errcode=$?
+		[ ! -z "$DIETIME" ] && sleep $DIETIME
 		start $2
+		[ $errcode -eq 0 ] && errcode=$?
 	;;
 	restart_dead)
 		restart_dead
+		errcode=$?
+	;;
+	status_all)
+		status_all
+		errcode=$?
 	;;
 
 	-V)
@@ -157,10 +234,10 @@ case "$1" in
 	;;
 	*)
 		echo "Usage: flint {start|stop|restart} projectname"
-		echo "       flint {start_all|stop_all|restart_all|restart_dead}"
+		echo "       flint {start_all|stop_all|restart_all|restart_dead|status_all}"
 		echo "       flint {--version|-V}"
 		exit 1
 	;;
 esac
-exit 0
+exit $errcode
 
