Adding options for maxrequests and maxchildren. Converting to native package format.

diff --git a/flint b/flint
--- a/flint
+++ b/flint
@@ -4,6 +4,8 @@ DJANGO_ROOT='/var/django'
 VIRTUALENV_ROOT="$DJANGO_ROOT/.virtualenvs"
 MINSPARE=4
 MAXSPARE=32
+MAXCHILDREN=32
+MAXREQUESTS=100
 RUN_DIR="/var/run/django"
 FASTCGI_USER="www-data"
 
@@ -53,7 +55,7 @@ start() {
 		return
 	fi
 
-	echo "source \"$virtualenv/bin/activate\" && python \"$project/manage.py\" runfcgi socket=$socket pidfile=$pid minspare=$MINSPARE maxspare=$MAXSPARE method=prefork daemonize=true && echo \"OK\" || echo \"Failed\" && deactivate" | su $FASTCGI_USER -c 'bash -s'
+	echo "source \"$virtualenv/bin/activate\" && python \"$project/manage.py\" runfcgi socket=$socket pidfile=$pid minspare=$MINSPARE maxspare=$MAXSPARE maxchildren=$MAXCHILDREN maxrequests=$MAXREQUESTS method=prefork daemonize=true && echo \"OK\" || echo \"Failed\" && deactivate" | su $FASTCGI_USER -c 'bash -s'
 }
 
 stop() {
